python main.py \
  --run_name "test_oneshot_compile" \
  --root_dir "exp" \
  --dataset_path ./benchmarks/verilogeval-syntax-hard.jsonl \
  --task "oneshot_fix_compile" \
  --agent_feedback "rag" \
  --language "verilog" \
  --model "DeepSeek-V3.2" \
  --pass_at_k "1" \
  --num_samples '1' \
  --compiler 'iverilog' \
  --verbose
